---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


# Reproducible Research: Peer Assessment 1
This file is the solution of the assignment


## Required libraries
```{r libraries}
# Load required libraries
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("data.table"))
```

## Loading and preprocessing the data
```{r readdata}
# Input files
file.zip <- "activity.zip"
file.csv <- "activity.csv"

# Load and process the data
dat <- unz(file.zip, file.csv) %>%
       read.csv(as.is = TRUE,
                colClasses = c("integer", "Date", "integer"),
                check.names = FALSE) %>%
       data.table

# Print data summary
summary(dat)
```


## What is mean total number of steps taken per day?
```{r meansteps}
# Calculate the total number of steps taken per day
total.steps <- dat[, sum(steps, na.rm = TRUE), by = date][,V1]

# Plot histogram of the total number of steps taken each day
hist(total.steps,
     main = "Total daily steps",
     xlab = "Number of steps",
     col = "lightblue3")

# Calculate the mean and median of the total number of steps taken per day
mean(total.steps)
median(total.steps)
```


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
